### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by bryson** [danzimm/background-matrix#8]
In stylesheets/background-matrix.less: Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by danzimm** [comment]
@bryson Thanks - this was taken off `apm` thought due to the fact that I no longer support it. Feel free to fork, fix and republish!

**Comment by bryson** [comment]
Gotcha, didn't even realize it was gone. Thanks!
